name: CI - Testes e Build

env:
  ZIP_NAME: pestto-latest.zip

on:
  push:
    branches: ['main']

jobs:
  # Job 1: Garantir que o código está funcionando
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install
      - run: npm run lint
      - run: npm run format:check
      - run: npm test

  # Job 2: Só roda se o 'test' terminar com sucesso
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install
      - name: Gerar version.js
        run: ./scripts/generate-version.sh "${{ github.run_number }}" "${GITHUB_SHA::7}"
      - run: npm run build
      - name: Salvar Artefato
        uses: actions/upload-artifact@v6
        with:
          name: pestto-latest-build
          path: ${{ env.ZIP_NAME }}
