name: CI - Testes e Build

env:
  ZIP_NAME: pestto-latest.zip

on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: Garantir que o código está funcionando
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test

  # Job 2: Só roda se o 'test' terminar com sucesso
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Gerar version.js
        run: |
          VERSION=$(npm pkg get version | tr -d '"')
          DATETIME=$(date +'%Y-%m-%d %H:%M')
          GIT_HASH=$(git rev-parse --short HEAD)
          INFO="Pestto v$VERSION ($DATETIME) [$GIT_HASH]"
          echo "const BUILD_INFO = '$INFO';" > version.js
          echo "🏗️  version.js gerado no CI"
      - run: npm run build
      - name: Salvar Artefato
        uses: actions/upload-artifact@v4
        with:
          name: pestto-latest-build
          path: ${{ env.ZIP_NAME }}